### ISSUE TITLE
 question from a smash fan

### ISSUE THREAD

**Issue by LkAD4** [VetriTheRetri/ssb-decomp-re#6]
In advance I thank you for your commitment to carrying out this project, although I don't know how I can see the progress of the **decompilation of Smash 64**, I have two questions, _how do you carry out the decompilation process and how could I be a tester of the project if possible_

**Comment by VetriTheRetri** [comment]
Hello! Progress can be checked in the following Discord server: https://discord.gg/P8H5YRCNBb

Decompilation is done by following the assembly (ASM) from a given ROM and translating it to a higher level language that produces a program with the same functionality as the original when compiled. In the case of SSB, we're writing C language code that compiles into the exact same bytes as the original developers' code.

Since this is a decompilation project, there's no "testing" involved in the usual sense, as we're only trying to match the original NTSC-U ROM, and when something goes wrong, we use sophisticated tools to track down where the problem stems from; if the ROM doesn't match, we can track down why, and if it does match, there's nothing to worry about, it's the exact same binary as what was released in the USA in March of 1999. As such, testing would only be feasible if new features were added to the game, which is not the case with the decompilation project, but definitely would be with other projects based on it that modify or add new functionality.

P.S. This branch of ssb-decomp-re will eventually become obsolete as we're in the process of making buildingRom the main branch and moving over files that have already been matched. If you want to build the decompilation yourself, follow the instructions on the buildingRom branch. You can modify certain (although for the time being, very simple) aspects of the game such as character special move attributes, however, adding or removing code will likely break the ROM when built due to not being fully shiftable yet.
